# Generated by Django 3.1.7 on 2023-10-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material', '0002_auto_20231014_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='categoria',
            field=models.CharField(choices=[('Papel', 'Papel'), ('Cartulina', 'Cartulina'), ('Carton', 'Carton'), ('Plastico', 'Plastico'), ('Tela', 'Tela')], default='Papel', max_length=20),
        ),
    ]
