# Generated by Django 3.1.7 on 2023-10-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material', '0004_auto_20231015_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='grosor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
