# Generated by Django 3.1.7 on 2024-03-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Terminado', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terminado',
            old_name='cantidad',
            new_name='distancia',
        ),
    ]
